### ISSUE TITLE
HttpClient doesn't work, no data on my static page

### ISSUE THREAD

**Issue by phil2strass** [SanderElias/ScullySampleApp#1]
Hello,
I'm completely baffled... I've wasted two weeks trying to figure out how to make Scully work. I followed your example, the official documentation but I can't get the data to load on my pages. How could we do that ? As simple as possible..

**Comment by SanderElias** [comment]
You want to embed some data into your page?
Look [here](https://github.com/SanderElias/ScullySampleApp/blob/main/src/app/user/user.component.ts#L44-L52), it shows how to use scullyTransferState to embed de data from en observable data completes

**Comment by phil2strass** [comment]
I've tried with your code, but nothing in the static file. I see one difference. I have "@scullyio/scully-plugin-puppeteer": "^2.1.32", in my package. You don't have it. In the documentation I read: WSL Pre-Requisites. Maybe I have to install that on my Win10.

I must point out that I know Angular well. Now with scully I feel like a loser for not getting the right result :)

**Comment by phil2strass** [comment]
I've created a repository with a simple code: https://github.com/phil2strass/scullyWithHttpIssue

The HttpClient for testing is in the "home" folder and I have no data in my static file.. I think I'm not the only one having this trouble with Scully.
